Allow multiple attempts at the decryption password

diff --git a/home/.chezmoiscripts/run_once_before_decrypt-private-key.sh.tmpl b/home/.chezmoiscripts/run_once_before_decrypt-private-key.sh.tmpl
--- a/home/.chezmoiscripts/run_once_before_decrypt-private-key.sh.tmpl
+++ b/home/.chezmoiscripts/run_once_before_decrypt-private-key.sh.tmpl
@@ -1,7 +1,18 @@
 #!/bin/sh
 
-if [ ! -f "${HOME}/.config/chezmoi/key.txt" ]; then
-  mkdir -p "${HOME}/.config/chezmoi"
-  {{ .chezmoi.executable }} age decrypt --output "${HOME}/.config/chezmoi/key.txt" --passphrase "{{ .chezmoi.sourceDir }}/key.txt.age"
-  chmod 600 "${HOME}/.config/chezmoi/key.txt"
+config_dir="${HOME}/.config/chezmoi"
+
+if [ ! -f "${config_dir}/key.txt" ]; then
+  mkdir -p "${config_dir}"
+
+  max_retry=10
+  counter=0
+  until {{ .chezmoi.executable }} age decrypt --output "${config_dir}/key.txt" --passphrase "{{ .chezmoi.sourceDir }}/key.txt.age"
+  do
+    [[ counter -eq $max_retry ]] && echo "Too many attempts, aborting." && exit 1
+    echo "Please try again."
+    ((counter++))
+  done
+
+  chmod 600 "${config_dir}/key.txt"
 fi
